### ISSUE TITLE
Share PCB files? [request]

### ISSUE THREAD

**Issue by DRSDavidSoft** [opendime/opendime#1]
Hi there,

The idea of this project is very promising, and IMO is has been designed and performed quite nicely. I'm particularly interested in your v2.0 design.

Since I'm designing a USB device with similar requirements (etc low-cost, and a nice design) I was wondering if it's possible for you to share the PCB design files? The term "open" in OpenDime got me wondering if the hardware is also open.

Anyways, thanks for your time, and I hope it's possible for your team to also share the PCB files on GitHub.

**Comment by doc-hex** [comment]
If you're starting a new design based on the Atmel (now Microchip) ATSAMD21 parts, I recommend this product from Adafruit: [Feather M0 Basic Proto - ATSAMD21 Cortex M0](https://www.adafruit.com/product/2772). You can get started with that assembled board, and when it's time to commericalize it, complete Eagle schematics and PCB layout files are [on github already!](https://github.com/adafruit/Adafruit-Feather-M0-Basic-Proto-PCB)
