### ISSUE TITLE
Was balance.py dropped in v2.4?

### ISSUE THREAD

**Issue by davidknezic** [opendime/opendime#12]
Hi there, just got notified by a friend that there is no `balance.py` on an Opendime they received from me.

I checked another `v2.4` Opendime and noticed the same. This repo also contains no such file.

Unfortunately though, the `README.md` still mentions the file, which can raise doubt about the authenticity of the Opendime.

Is it correct that `balance.py` was dropped in `v2.4` and if so would it be possible to remove all references to it in a future iteration?

**Comment by doc-hex** [comment]
Yes, `balance.py` was removed because it's hard to keep the blockchain explorer API's current.

For your friends, they can compare file contents to this repo (in `/v2.4/` tree) to gain trust.

I've made a note to update the README which references the missing file.

**Comment by davidknezic** [comment]
Will let them know. Thank you @peter-conalgo!

**Comment by tomcjohn** [comment]
Likewise @doc-hex there is another reference that could use updating as well please, on the Opendime FAQ page - https://opendime.com/faq#withdraw - in the `How do I get funds out?` section it says:
> There is also a python program (advanced/balance.py) which can be used to move the funds out when unsealed.

Thanks!
