### ISSUE TITLE
What material is the transparent wrap around the open dime?

### ISSUE THREAD

**Issue by nixoye** [opendime/opendime#2]
I’m wondering what material the transparent cover around the individual open dime is and if it makes it water proof?

**Comment by doc-hex** [comment]
Sorry it's not really waterproof, although some of our customers have run them through the laundry with good results... YMMV!

**Comment by sabotagebeats** [comment]
> Sorry it's not really waterproof, although some of our customers have run them through the laundry with good results... YMMV!

thanks this is good info
