### ISSUE TITLE
Is it possible to reveal the public key?

### ISSUE THREAD

**Issue by mikispag** [opendime/opendime#4]
Hello,

is it possible to reveal the public key of an unsealed OPENDIME?
This would make multisig + timelocks possible.

**Comment by doc-hex** [comment]
I believe the public key for an Opendime can be calculated from the signature it puts on the `verify.txt` (or `verify2.txt`) message. Someday we will publish an article about how to do that, but we haven't gotten to it yet. This approach will work on unsealed and sealed Opendimes.

Maybe in a future version of the firmware we can put that into the python code that travels with Opendimes.

**Comment by timchurchard** [comment]
@mikispag I realise this is 3y/o now but I wrote some code to derive the public key from the signature in the opendime verify.txt and produce more addresses. https://github.com/timchurchard/opendime-utils

**Comment by doc-hex** [comment]
Very nice! I'm sure many people will find that useful.
