### ISSUE TITLE
LTC V2.3 trustme.py "Additional low-level checks" error out with "usb.core.NoBackendError: No backend available"

### ISSUE THREAD

**Issue by sabotagebeats** [opendime/opendime#5]
`PS D:\advanced> python trustme.py

Opendime USB at: D:\

 Wallet address: redacted

Opendime Version: 2.3.0

      time: 20171018.143523
       git: master@8fb7cfd
      coin: LTC
    serial: redacted

Additional low-level checks:
Traceback (most recent call last):
  File "trustme.py", line 31, in <module>
    import pycode.trust_me; pycode.trust_me.main()
  File "..\support\pycode.zip\pycode\trust_me.py", line 260, in main
  File "..\support\pycode.zip\pycode\trust_me.py", line 77, in lowlevel_tests
  File "..\support\pycode.zip\pycode\trust_me.py", line 60, in __init__
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\usb\core.py", line 1263, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available`

**Comment by sabotagebeats** [comment]
python 3.6 windows 10

**Comment by sabotagebeats** [comment]
pip show pyusb
Name: pyusb
Version: 1.0.2
Summary: Python USB access module
Home-page: http://walac.github.io/pyusb
Author: Wander Lairson Costa
Author-email: wander.lairson@gmail.com
License: BSD

**Comment by doc-hex** [comment]
Sorry, I don't know what's involved in installing libusb under Windows. For the extra verification steps, it needs to be installed (and working) already before `trustme.py` runs.

**Comment by sabotagebeats** [comment]
is it recommended to do this on linux then?

**Comment by doc-hex** [comment]
Linux or MacOS, yes.
