### ISSUE TITLE
python balance.py returns no balance and crashes

### ISSUE THREAD

**Issue by xavierfiechter** [opendime/opendime#6]
```
python balance.py
Downloading pycoin (wait)...

Opendime USB at: /media/pi/OPENDIME

Wallet address: xxxxxxxxxxxxxxxxxxxxxxxxxxx


Current Balance

 Chain.so            None
 Local Bitcoins      ERROR [404: Not Found]
 Blockchain.info     ERROR [500: Internal Server Error]
 BitPay              None
 Blockcypher         ERROR [429: Too Many Requests]
 Blockr.io           Traceback (most recent call last):
  File "balance.py", line 17, in <module>
    import pycode.od_wallet; pycode.od_wallet.main()
  File "../support/pycode.zip/pycode/od_wallet.py", line 145, in main
  File "../support/pycode.zip/pycode/od_wallet.py", line 70, in find_balance
AttributeError: 'exceptions.ValueError' object has no attribute 'code'
```

**Comment by doc-hex** [comment]
Unfortunately, `balance.py` has to rely on centralized services for its data. This lacks privacy and is ultimately untenable as they come and go much faster than we can update the product. [Yesterday we closed the books on v2.4.0](https://github.com/opendime/opendime/commit/2d0faa64299f57e48c1a485bc7ac85c01fcabb45) of the firmware (which will be shipped on v4 of the Opendime hardware) and we kept the `balance.py` code in, but did not update or modernize it.
We will probably remove this feature in the next version of the product. 

I recommend using block explorer websites. The links provided by the `index.html` file have been updated. You also have the option of using <opendime.com> for checking balances and verifying signatures.

Use a Tor browser to visit [Blockstream's onion address on the Tor network](http://explorerzydxu5ecjrkwceayqybizmpjjznk5izmitf2modhcusuqlid.onion/) for the best privacy.
