### ISSUE TITLE
When SegWit?

### ISSUE THREAD

**Issue by Sjors** [opendime/opendime#9]
In particular, I'd like to get a bech32 address. Signature validation could presumably use [BIP322](https://github.com/bitcoin/bips/blob/master/bip-0322.mediawiki)

**Comment by nvk** [comment]
Sorry, no plans at this point. OD is meant to be backwards compatible. Maybe in the future we have an option at initialization time.

**Comment by woutersamaey** [comment]
Still nothing 2 years later?

**Comment by Sjors** [comment]
Or just Taproot :-) No more public key hash.

**Comment by doc-hex** [comment]
Hmm... let me just say that BIP-178 is presently top of mind for me.

**Comment by Sjors** [comment]
@doc-hex you may want to consider output descriptors instead, you can put a private key in those too. Specifically [BIP-386](https://github.com/bitcoin/bips/blob/master/bip-0386.mediawiki)
